#! /bin/bash
set -e

if [ -f /etc/init.d/monasca-agent ]; then
    if which invoke-rc.d >/dev/null 2>&1; then
        invoke-rc.d monasca-agent stop || true
    else
        /etc/init.d/monasca-agent stop || true
    fi
fi

#DEBHELPER#
exit 0
