#! /bin/bash
set -e

if [ "$1" = purge ]; then
    update-rc.d jahmon-agent remove
    deluser jahmon-agent
    [ -h /usr/bin/jahmon-agent ] && rm /usr/bin/jahmon-agent
    [ -h /etc/jahmon-agent/config.py ] && rm /etc/jahmon-agent/config.py
    [ -h /usr/bin/dogstatsd ] && rm /usr/bin/dogstatsd

fi

exit 0
