#! /bin/bash
set -e

if [ -f /etc/init.d/mon-agent ]; then
    if which invoke-rc.d >/dev/null 2>&1; then
        invoke-rc.d mon-agent stop || true
    else
        /etc/init.d/mon-agent stop || true
    fi
fi
